### ISSUE TITLE
App store release

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/files_emailviewer#8]
- [x] Linter 
- [x] Psalm
- [x] SPDX
- [x] Setup Check for correct configuration
- [x] ~If possible, Tooltip when xhr request failed~ Not possible
- [x] Buildfile
- [x] Dependabot
- [x] Keys: https://github.com/nextcloud/app-certificate-requests/pull/734
- [x] l10n: https://github.com/nextcloud/docker-ci/issues/672
- [x] Change default branch to main

**Comment by Mer0me** [comment]
I've just seen that on the Hub 9 presentation. When will it be available on the App Store ?

**Comment by ChristophWurst** [comment]
@kesselb could you please update the ticket description with the (open) todos? thanks

**Comment by ChristophWurst** [comment]
@Mer0me the app will be available soon

**Comment by kesselb** [comment]
Done
